services:
  bandersnatch:
    image: pypa/bandersnatch:latest
    platform: linux/amd64
    volumes:
      - "./bandersnatch.conf:/conf/bandersnatch.conf"
      - "./data_bandersnatch:/srv/pypi/web"
    networks:
      - mirror_net
    command:
      - "python"
      - "/bandersnatch/src/runner.py"
      - "--force-check"
      - "true"
      - "3600" # hourly
  banderctl:
    image: harbor.services.osism.tech/osism/banderctl:latest
    platform: linux/amd64
    volumes:
      - "./bandersnatch.conf:/bandersnatch.conf"
    networks:
      - mirror_net
    command:
      - "uvicorn"
      - "app.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "80"
      - "--root-path"
      - "/banderctl"
  nginx:
    image: nginx:latest
    platform: linux/amd64
    volumes:
      - "./data_bandersnatch:/data/pip:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    networks:
      - mirror_net

networks:
  mirror_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

